version: 0.0
os: linux
files:
  - source: /
    destination: /opt/dokv
hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
