version: 0.0
os: linux
files:
  - source: /
    destination: /opt/dokv
  - source: /scripts/dokv.service
    destination: /etc/systemd/system
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      runas: root
